import { execSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import type { AnnotatedScreenshot } from "./types.js";

const SCREENSHOT_MARKER_START = "<!-- pr-visual-screenshots -->";
const SCREENSHOT_MARKER_END = "<!-- /pr-visual-screenshots -->";

function buildScreenshotMarkdown(
  screenshots: AnnotatedScreenshot[],
  repoRoot: string
): string {
  const grouped = new Map<string, AnnotatedScreenshot[]>();
  for (const s of screenshots) {
    const key = `${s.viewport}-${s.colorScheme}`;
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key)!.push(s);
  }

  let md = "";
  for (const [key, shots] of grouped) {
    const [viewport, colorScheme] = key.split("-");
    md += `\n### ${viewport} (${colorScheme})\n\n`;
    for (const shot of shots) {
      const relativePath = path.relative(repoRoot, shot.path);
      md += `**${shot.caption}**\n`;
      md += `![${shot.caption}](${relativePath})\n\n`;
    }
  }

  return md;
}

function getPRBody(prNumber: number): string {
  return execSync(`gh pr view ${prNumber} --json body -q .body`, {
    encoding: "utf-8",
    timeout: 10_000,
  }).trim();
}

function updatePRBody(prNumber: number, newBody: string): void {
  // Write body to temp file to avoid shell escaping issues
  const tmpFile = path.join(
    process.env.TMPDIR ?? "/tmp",
    `pr-visual-body-${Date.now()}.md`
  );
  fs.writeFileSync(tmpFile, newBody, "utf-8");
  try {
    execSync(`gh pr edit ${prNumber} --body-file ${JSON.stringify(tmpFile)}`, {
      stdio: "pipe",
      timeout: 15_000,
    });
  } finally {
    fs.unlinkSync(tmpFile);
  }
}

export function patchPRBodyWithScreenshots(
  prNumber: number,
  screenshots: AnnotatedScreenshot[],
  repoRoot: string
): void {
  const currentBody = getPRBody(prNumber);
  const screenshotSection = [
    SCREENSHOT_MARKER_START,
    "\n## Visual Documentation\n",
    buildScreenshotMarkdown(screenshots, repoRoot),
    SCREENSHOT_MARKER_END,
  ].join("\n");

  let newBody: string;
  const markerRegex = new RegExp(
    `${escapeRegex(SCREENSHOT_MARKER_START)}[\\s\\S]*?${escapeRegex(SCREENSHOT_MARKER_END)}`
  );

  if (markerRegex.test(currentBody)) {
    // Idempotent update — replace existing section
    newBody = currentBody.replace(markerRegex, screenshotSection);
  } else {
    // First time — append to bottom
    newBody = `${currentBody}\n\n${screenshotSection}`;
  }

  updatePRBody(prNumber, newBody);
  console.log(`  PR #${prNumber} body updated with screenshots`);
}

export function addVideoComment(
  prNumber: number,
  videoPath: string,
  label: string
): void {
  const fileName = path.basename(videoPath);
  const commentBody = [
    `### Video Walkthrough — ${label}`,
    "",
    `> Captioned video: \`${fileName}\``,
    "",
    "_Video file is available in the PR artifacts._",
    "",
    "---",
    "_Generated by pr-visual_",
  ].join("\n");

  execSync(`gh pr comment ${prNumber} --body ${JSON.stringify(commentBody)}`, {
    stdio: "pipe",
    timeout: 15_000,
  });
  console.log(`  Video comment added to PR #${prNumber}: ${label}`);
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
